
# build as a docker container and upload to artifactory
docker-build: &docker-build
  dockerfile: Dockerfile
  image: plugins/docker
#  registry: index.docker.io/v1/vincentko89
  secrets: [ docker_username, docker_password ]
  repo: vincentko89/stockanalysis

# pipeline steps below
pipeline:

  #GRADLE BUILD
  build:
    when:
      event:
        - push
    image: java:openjdk-8
    secrets: [ docker_username, docker_password ]
    environment:
      - GRADLE_USER_HOME=.gradle
    commands:
      - ./gradlew clean build --info --stacktrace

  #DOCKER BUILD - LATEST - ARTIFACTORY
  docker-build-dockerhub-dev-publish-latest:
    when:
      branch: [ dev, VL* ]
      event: [ push ]
#      ref: refs/tags/dev*
    <<: *docker-build
    build_args: VERSION=${DRONE_COMMIT:0:8}
    tag:
      - latest
      - "${DRONE_COMMIT:0:8}"
#
#  # DOCKER BUILD - RELEASE - ARTIFACTORY##
#  docker-build-artifactory-master-publish-release:
#    when:
#      branch: [ master ]
#      event: [ push ]
#    <<: *docker-build
#    build_args: VERSION=${DRONE_COMMIT:0:8}
#    tag:
#      - latest
#      - "${DRONE_COMMIT:0:8}"
#
#  deployment-dev-east1:
#    when:
#      branch: [ dev ]
#      event: [ push ]
#    image: docker.target.com/drone/drone-kubernetes:latest
#    secrets:
#      - source: kube_config
#        target: kube_config
#    context: minikube
#    filename:
#      - kube/us-east1-dev/
#    status: deployment/voltron-ppa-service
#    status_timeout: 10m
#    images:
#      stockanalysis: "vincentko89/stockanalysis:${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}"